substitutions:
    name: 'gosund-p1'
    friendly_name: 'Gosund P1'
    contact_1_name: 'Steckdose 1'
    contact_2_name: 'Steckdose 2'
    contact_3_name: 'Steckdose 3'
    reboot_timeout: '15min'

##############################################
# General Settings
##############################################
esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: true
  project:
    name: "Sebastian Schmidt.Gosund P1"
    version: "0.1.0"

esp8266:
  board: esp8285
  restore_from_flash: true

api:
  reboot_timeout: '${reboot_timeout}'
ota:

logger:
  baud_rate: 0

wifi:
  ap:
    ssid: '${devicename}'
    manual_ip:
      static_ip: 192.168.4.1
      gateway: 192.168.4.1
      subnet: 255.255.255.0

captive_portal:

dashboard_import:
  package_import_url: github://sebrauschmidt/device-templates/power-strips/gosund-p1.yaml@main
  import_full_config: false
##############################################
# Components
##############################################
uart:
  rx_pin: GPIO3
  baud_rate: 4800

binary_sensor:
  - platform: gpio
    id: powerbutton
    pin:
      number: GPIO16
      inverted: true
  - platform: template
    id: buttonrelay1
    internal: true
    on_press:
      then:
        - if:
            condition:
              switch.is_off: child_lock
            then:
              - switch.toggle: relay1
    filters:
      - delayed_off: 100ms
  - platform: template
    id: buttonrelay2
    internal: true
    on_press:
      then:
        - if:
            condition:
              switch.is_off: child_lock
            then:
              - switch.toggle: relay2
    filters:
      - delayed_off: 100ms
  - platform: template
    id: buttonrelay3
    internal: true
    on_press:
      then:
        - if:
            condition:
              switch.is_off: child_lock
            then:
              - switch.toggle: relay3
    filters:
      - delayed_off: 100ms

switch:
  - platform: gpio
    id: led
    name: "Status LED"
    pin:
      number: GPIO2
      inverted: true
    restore_mode: RESTORE_DEFAULT_ON
    entity_category: 'config'
  - platform: gpio
    name: '${contact_1_name}'
    id: relay1
    pin:
      number: GPIO14
  - platform: gpio
    name: '${contact_2_name}'
    id: relay2
    pin:
      number: GPIO12
  - platform: gpio
    name: '${contact_3_name}'
    id: relay3
    pin:
      number: GPIO13
  - platform: gpio
    name: 'USB'
    id: relay4
    restore_mode: RESTORE_DEFAULT_OFF
    pin:
      number: GPIO5
      inverted: true
  - platform: template
    name: "Kindersicherung"
    id: child_lock
    entity_category: config
    optimistic: true

sensor:
  - platform: uptime
    name: 'Laufzeit'
    update_interval: 300s
    entity_category: 'diagnostic'
  - platform: wifi_signal
    name: 'WiFi Signalstärke'
    update_interval: 60s
    entity_category: 'diagnostic'
  - platform: cse7766
    current:
      id: ampere
      name: 'Strom'
    voltage:
      id: volt
      name: 'Spannung'
      filters:
        - lambda: return x * 2.34245;
    power:
      name: 'Leistung'
      id: watt
      filters:
        - lambda: return x * 2.34245;
  - platform: total_daily_energy
    name: 'Verbrauch'
    power_id: watt
    filters:
      - multiply: 0.001
    unit_of_measurement: kWh
  - platform: adc
    pin: GPIO17
    id: gpio17
    internal: true
    update_interval: 0.1s
    filters:
      - lambda: |-
          if(x >= 0.60 && x < 0.90){
            id(buttonrelay1).publish_state(true);
          } else if(x >= 0.30 && x < 0.60){
            id(buttonrelay2).publish_state(true);
          }
          else if(x > 0.10 && x < 0.30){
            id(buttonrelay3).publish_state(true);
          } else {
            id(buttonrelay1).publish_state(false);
            id(buttonrelay2).publish_state(false);
            id(buttonrelay3).publish_state(false);
          }
          return{};

button:
  - platform: restart
    name: "Neustarten"

text_sensor:
  - platform: version
    name: 'ESPHome Version'

time:
  - platform: sntp
    id: sntp_time
    timezone: Europe/Berlin
    servers:
      - 0.pool.ntp.org
      - 1.pool.ntp.org
      - 2.pool.ntp.org