substitutions:
  devicename: "wetterstation"
  upper_devicename: "Wetterstation"
  ip_address: ""

dashboard_import:
  package_import_url: https://git.sebschmidt.de/homeassistant/device-templates/raw/branch/main/sensors/esp32_lolin_weather_station.yaml
  import_full_config: false

esphome:
  name: ${devicename}
  friendly_name: ${upper_devicename}
  name_add_mac_suffix: true
  project:
    name: sebrauschmidt.esp32_lolin_weather_station
    version: "0.1"

esp32:
  board: lolin32
  framework:
    type: esp-idf
    version: recommended

logger:

api:

ota:

wifi:
  ap:
    password: "esphomeFTW"

captive_portal:

i2c:
  sda: 23
  scl: 22
  scan: true
  id: bus_a

sensor:
  - platform: bme280_i2c
    temperature:
      name: Temperatur
      oversampling: 16x
    pressure:
      name: Luftdruck
    humidity:
      name: Luftfeuchtigkeit
    address: 0x77
    update_interval: 10s
  - platform: bh1750
    name: Helligkeit
    address: 0x23
    update_interva: 10s
  - platform: uptime
    name: 'Laufzeit'
    update_interval: 300s
    entity_category: 'diagnostic'
  - platform: wifi_signal
    name: 'WiFi Signalstärke'
    update_interval: 60s
    entity_category: 'diagnostic'

button:
  - platform: restart
    name: "Restart"

text_sensor:
  - platform: version
    name: 'ESPHome Version'

