substitutions:
  devicename: "partikelsensor"
  upper_devicename: "Partikelsensor"
  ip_address: ""

dashboard_import:
  package_import_url: https://git.sebschmidt.de/homeassistant/device-templates/raw/branch/main/sensors/ikea_vindriktning_esp32.yaml
  import_full_config: false

esphome:
  name: ${devicename}
  friendly_name: ${upper_devicename}
  name_add_mac_suffix: true
  project:
    name: sebrauschmidt.ikea_vindriktning_esp32
    version: "0.1"

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:

api:

ota:

wifi:
  ap:
    password: "esphomeFTW"

captive_portal:

uart:
  rx_pin: GPIO16
  baud_rate: 9600

sensor:
  - platform: pm1006
    pm_2_5:
      name: 'Partikel'
