---
substitutions:
  name: "shelly-1-mini-g3"
  friendly_name: "Shelly 1 Mini Gen3"
  logger_level: INFO

##########################################################
# General settings                                       #
##########################################################
esphome:
  name_add_mac_suffix: true
  name: "${name}"
  friendly_name: "${friendly_name}"
  project:
    name: "Sebastian Schmidt-Eichler.Shelly 1 Mini Gen 3"
    version: "0.2.3"

dashboard_import:
  package_import_url: github://sebrauschmidt/device-templates/relays/shelly-1-mini-gen3.yaml@main
  import_full_config: false

esp32:
  board: esp32-c3-devkitm-1
  flash_size: 8MB
  framework:
    type: esp-idf
    version: recommended
    sdkconfig_options:
      COMPILER_OPTIMIZATION_SIZE: y

api:
  reboot_timeout: 0s
  on_client_connected:
    then:
      if:
        condition:
          and:
            - lambda: 'return id(mode_select).current_option() == "detached offline fallback";'
            - switch.is_off: ota_mode
        then:
          - switch.turn_on: relay_switch
  on_client_disconnected:
    then:
      if:
        condition:
          and:
            - binary_sensor.is_off: switch_input
            - switch.is_off: ota_mode
        then:
          - switch.turn_off: relay_switch

ota:
  - platform: esphome

logger:
  level: '${logger_level}'

wifi:
  ap:
    ssid: '${name}'
    manual_ip:
      static_ip: 192.168.4.1
      gateway: 192.168.4.1
      subnet: 255.255.255.0

captive_portal:

web_server:
  port: 80
  include_internal: true
  ota: False
  version: 3

##########################################################
# Components                                             #
##########################################################

sensor:
  - platform: ntc
    name: "Temperature"
    sensor: temp_resistance_reading
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    icon: "mdi:thermometer"
    calibration:
      b_constant: 3350
      reference_resistance: 10kOhm
      reference_temperature: 298.15K
  - platform: resistance
    id: temp_resistance_reading
    sensor: temp_analog_reading
    configuration: DOWNSTREAM
    resistor: 10kOhm
  - platform: adc
    id: temp_analog_reading
    pin: GPIO03
    attenuation: 12db
  - platform: uptime
    name: "Laufzeit"
    update_interval: 60s
    entity_category: "diagnostic"
  - platform: wifi_signal
    name: "WiFi Signalstärke"
    update_interval: 60s
    entity_category: "diagnostic"

text_sensor:
  - platform: version
    name: "Version"
    hide_timestamp: true
    entity_category: "diagnostic"
  - platform: wifi_info
    ip_address:
      name: "IP-Adresse"
    mac_address:
      name: "MAC-Adresse"
    power_save_mode:
      name: "Energiesparmodus"

button:
  - platform: restart
    name: "Neustarten"
    entity_category: "diagnostic"
  - platform: safe_mode
    name: "Neustarten (Safe Mode)"
    entity_category: "diagnostic"

output:
  - platform: gpio
    id: relay
    pin: 7

switch:
  - platform: output
    name: "Relais"
    id: relay_switch
    output: relay
  - platform: template
    name: "OTA Modus"
    id: ota_mode
    optimistic: true

binary_sensor:
  - platform: gpio
    name: "Schalter"
    id: switch_input
    pin:
      number: 10
      inverted: true
    on_state_change:
      if:
        condition:
          or:
            - and:
              - not:
                  api.connected:
                    state_subscription_only: true
              - lambda: 'return id(mode_select).current_option() == "detached offline fallback";'
              - switch.is_off: ota_mode
            - lambda: 'return id(mode_select).current_option() == "attached";'
        then:
          if:
            condition:
              binary_sensor.is_on: switch_input
            then:
              - switch.turn_on: relay_switch
            else:
              - switch.turn_off: relay_switch

    filters:
      - delayed_on_off: 50ms
  - platform: gpio
    name: "Knopf"
    pin:
      number: 1
      inverted: true
      mode:
        input: true
        pullup: true

select:
  - platform: template
    name: "Switch Mode"
    id: mode_select
    optimistic: true
    restore_value: true
    options:
      - attached
      - detached
      - detached offline fallback
    entity_category: "config"

status_led:
  pin:
    number: 0
    inverted: true
