substitutions:
    devicename: "gosund-sp1"
    friendly_name: 'Gosund SP1'
    contact_name: 'Schalter'
    reboot_timeout: '15min'

##############################################
# General Settings
##############################################
esphome:
  name: ${devicename}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: true
  project:
    name: sebrauschmidt.gosund-sp1
    version: "1.0"

esp8266:
  board: esp8285
  restore_from_flash: true

api:
  reboot_timeout: '${reboot_timeout}'

ota:

logger:
  baud_rate: 0

wifi:
  ap:
    ssid: '${devicename}'

captive_portal:

dashboard_import:
  package_import_url: github://sebrauschmidt/device-templates/power-plugs/gosund-sp1.yaml@main
  import_full_config: false

##############################################
# Components
##############################################

binary_sensor:
  - platform: gpio
    name: 'Taste'
    pin:
      number: GPIO3
      inverted: true
    id: powerbutton
    on_press:
      then:
        - if:
            condition:
              switch.is_off: child_lock
            then:
              - switch.toggle: relay

switch:
  - platform: gpio
    name: 'LED'
    id: led
    pin:
      number: GPIO1
      inverted: true
  - platform: gpio
    name: '${contact_name}'
    pin:
      number: GPIO14
    id: relay
    on_turn_on:
      - switch.turn_on: led
    on_turn_off:
      - switch.turn_off: led
    restore_mode: RESTORE_DEFAULT_OFF
  - platform: template
    name: "Kindersicherung"
    id: child_lock
    entity_category: config

sensor:
  - platform: hlw8012
    sel_pin:
      number: GPIO12
      inverted: true
    cf_pin:
      number: GPIO04
    cf1_pin:
      number: GPIO05
    current_resistor: 0.00221
    voltage_divider: 871
    current:
      id: ampere
      name: 'Strom'
      unit_of_measurement: A
    voltage:
      id: volt
      name: 'Spannung'
      unit_of_measurement: V
    power:
      id: watt
      name: 'Leistung'
      unit_of_measurement: W
    change_mode_every: 8
    update_interval: 10s
  - platform: total_daily_energy
    name: 'Verbrauch'
    power_id: watt
    filters:
      - multiply: 0.001
    unit_of_measurement: kWh
  - platform: uptime
    name: 'Laufzeit'
    update_interval: 300s
    entity_category: 'diagnostic'
  - platform: wifi_signal
    name: 'WiFi Signalstärke'
    update_interval: 60s
    entity_category: 'diagnostic'


button:
  - platform: restart
    name: 'Restart'

text_sensor:
  - platform: version
    name: 'ESPHome Version'

time:
  - platform: sntp
    id: sntp_time
    timezone: Europe/Berlin
    servers:
      - 0.pool.ntp.org
      - 1.pool.ntp.org